# Generated by Django 4.0.10 on 2023-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCount',
            fields=[
                ('compound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('compound_name', models.CharField(max_length=255)),
                ('compound_count', models.IntegerField()),
            ],
            options={
                'db_table': 'compound_count_data',
            },
        ),
    ]
